doctrine:
    dbal:
        host: '%env(resolve:MYSQL_HOST)%'
        user: '%env(resolve:MYSQL_USER)%'
        dbname: '%env(resolve:MYSQL_USER)%'
        password: '%env(resolve:MYSQL_USER)%'
        charset: utf8mb4
        default_table_options:
            charset: utf8mb4
            collate: utf8mb4_unicode_ci
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
doctrine_migrations:
    migrations_paths:
        'App\Migrations': 'src/Migrations'
