framework:
    annotations:
        enabled: true
    serializer:
        enabled: true
    validation:
        enabled: true
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: null
        cookie_secure: auto
        cookie_samesite: lax
    php_errors:
        log: true
