version: '3.0'
services:
    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
        depends_on:
            - php-fpm
    php-fpm:
        build: ./docker/php-fpm
        ports:
            - "9000:9000"
        links:
            - mysql
        volumes:
            - ./:/var/www/html
    mysql:
        image: mysql:5.7.19
        environment:
            MYSQL_DATABASE: crudnotes
            MYSQL_USER: crudnotes
            MYSQL_PASSWORD: crudnotes
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
