version: '3.0'
services:
    composer:
        image: composer:1.8.6
        volumes:
            - ./:/var/www/html
        command: >
            bash -c "cd /var/www/html
            && composer i"
    nginx:
        image: nginx:stable-alpine
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./docker/nginx/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
        depends_on:
            - php-fpm
    php-fpm:
        build: ./docker/php-fpm
        ports:
            - "9000:9000"
        depends_on:
            - composer
        links:
            - mysql
        volumes:
            - ./:/var/www/html
        command: >
            sh -c "cd /var/www/html
            && bin/console doctrine:migrations:migrate -n
            && bin/console doctrine:fixtures:load -n
            && php-fpm"
    mysql:
        image: mysql:5.7.19
        environment:
            MYSQL_DATABASE: crudnotes
            MYSQL_USER: crudnotes
            MYSQL_PASSWORD: crudnotes
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
